<script src="{{ asset('global/js/jquery.js') }}"></script>
<script src="{{ asset('global/js/jquery-migrate-1.2.1.min.js') }}"></script>
<script src="{{ asset('global/js/jquery-ui.js') }}"></script>
<script src="{{ asset('global/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js') }}"></script>
<script src="{{ asset('global/js/html5shiv.js') }}"></script>
<script src="{{ asset('global/js/respond.min.js') }}"></script>
<script src="{{ asset('global/plugins/slimScroll/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('global/plugins/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('global/plugins/iCheck/custom.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-metisMenu/jquery.menu.min.js') }}"></script>
<script src="{{ asset('plugins/jquery.blockUI.js') }}"></script>
<script src="{{ asset('global/js/app.js') }}"></script>
<script src="{{ asset('js/quick-sidebar.js') }}"></script>
<script src="{{ asset('js/admin-setting.js') }}"></script>
<script src="{{ asset('js/layout.js') }}"></script>
{{-- <script src="{{ asset('plugins/flot-chart/jquery.flot.js') }}"></script> --}}
{{-- <script src="{{ asset('plugins/flot-chart/jquery.flot.animator.min.js') }}"></script>
<script src="{{ asset('plugins/flot-chart/jquery.flot.resize.min.js') }}"></script>
<script src="{{ asset('plugins/flot-chart/jquery.flot.time.min.js') }}"></script> --}}
<script src="{{ asset('plugins/rickshaw/vendor/d3.v3.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Class.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Compat.ClassList.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Graph.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Graph.Renderer.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Graph.Renderer.Area.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Graph.HoverDetail.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Graph.Legend.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/src/js/Rickshaw.Fixtures.RandomData.js') }}"></script>
<script src="{{ asset('plugins/rickshaw/extensions.js') }}"></script>
<script src="{{ asset('plugins/jquery-sparkline/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('js/index.js') }}"></script>
<script src="{{ asset('plugins/fullcalendar/moment.min.js') }}"></script>
<script src="{{ asset('plugins/fullcalendar/fullcalendar.min.js') }}"></script>
<script src="{{ asset('js/pages/fullcalendar.js') }}"></script>
<script src="{{ asset('plugins/datatables/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('js/table-datatables.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<script src="{{ asset('js/form-editors.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ asset('plugins/datetimepicker/jquery.datetimepicker.js') }}"></script>
<script src="{{ asset('plugins/timepicker/jquery.timepicker.min.js') }}"></script>
<script src="{{ asset('plugins/selectize/js/standalone/selectize.js') }}"></script>
<script src="{{ asset('plugins/clockpicker/js/bootstrap-clockpicker.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap-slider/js/bootstrap-slider.js') }}"></script>
<script src="{{ asset('plugins/jquery-file-input/file-input.js') }}"></script>
<script src="{{ asset('js/form-plugins.js') }}"></script>


<script src="{{ asset('js/axios/axios.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-validate/jquery.validate.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.7.1/viewer.min.js" integrity="sha512-G1jR8u8V4AZA3cNtfjtjokzZKBY2LW4VmjzVZxDf+ZgARkVEb2TKQICeVGc5L2V0v8Fjn6t6ew05G95IFvLCIA==" crossorigin="anonymous"></script>
